# Generated by Django 5.0.2 on 2024-02-22 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('content', models.CharField(max_length=100, verbose_name='content')),
                ('article_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='article.article')),
            ],
        ),
    ]
