# Generated by Django 5.0.2 on 2024-02-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='article_id',
            new_name='article',
        ),
    ]
